LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=crtbegin_dynamic.o
LOCAL_BUILT_MODULE_STEM:=crtbegin_dynamic.o
LOCAL_STRIP_MODULE:=
LOCAL_MODULE := crtbegin_dynamic
LOCAL_MODULE_STEM:=crtbegin_dynamic.o
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib/
LOCAL_MODULE_OWNER := system
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=
include $(BUILD_PREBUILT)
